# -*- coding: utf-8 -*-
"""Activity_1_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1coi1aHJ9NPaOT2korsf6qhUGG1fNYZPk
"""

triangle_area = lambda b, h: (h*0.5)*b

def triangle_area(b, h):
    """Finds the area of a triangle

    Args:
        b: a number, base
        h: a number, height

    Returns:
        A number that is the product of the base and height divided by 2
    """
    output = (h*0.5)*b
    return output

def test_triangle_area():
  assert triangle_area(1, 2) == 1
  assert triangle_area(2, 3) == 3
  assert triangle_area(3, 4) == 6
  assert triangle_area(4, 0) == 0
  assert triangle_area(0, 5) == 0
test_triangle_area()

help(triangle_area)